name: 中青看点6

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/licky009/js.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【中青看点6】'
        run: |
          cd ~/js   
          node Task/youth6.js
